### ISSUE TITLE
Issue based workflow?

### ISSUE THREAD

**Issue by 213edu** [Gator-Coin/blockchain#1]
- we plan the features and core components of gator coin
- create issues on the repo for each feature and a list of broken-down tasks to implement as checkboxes, assign people to work on the issue
- create your own dev branch when working on a feature
- once the stuff you work on is finished or need review you push it to your dev branch and create a pull request linking to the issue
- when everything looks good, have someone review your code and merge it into development then rinse and repeat for the rest of the features
- when we reach a milestone and test our codes thoroughly we can merge development into master for releases

thoughts?

**Comment by Miguel619** [comment]
This is a great idea, we will need to train our team to use these techniques once we have the coin up and functioning. Thank you!
